Gruntwork patcher
Altalogy/gruntwork-io.github.io pull request #5
Opened 2022-09-20 10:58 UTC by lubiarz-oliwia

2022-09-21 12:51 UTC, klijakub commented
@lubiarz-oliwia 
Export this image in higher quality (@x2) 
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/4997537/191508191-761fbafe-f8ba-4aa0-a8f2-fcd8d4ceb7ad.png">

2022-09-21 13:28 UTC, klijakub requested changes

2022-09-21 13:28 UTC, klijakub commented on assets/css/global.scss
> +
Should be in `patcher.scss`

2022-09-21 13:28 UTC, klijakub commented on assets/css/pages/patcher.scss
> +          // overflow: hidden;
Remove comment

2022-09-21 13:28 UTC, klijakub commented on assets/css/pages/patcher.scss
> +          // margin-top: -1px;
Remove comment

2022-09-21 13:28 UTC, klijakub commented on assets/css/pages/patcher.scss
> +        }
Do we need this?

2022-09-21 13:37 UTC, klijakub commented
<img width="400" alt="image" src="https://user-images.githubusercontent.com/4997537/191518695-631da09f-f1e4-4631-8f3f-2c03f6366807.png">
Icon isn't sharp, poor quality export

2022-09-21 13:58 UTC, klijakub commented
![image](https://user-images.githubusercontent.com/4997537/191524129-009caa8c-d0aa-4602-9c70-3aadabd6fc76.png)
Fix hover issue

2022-09-21 14:11 UTC, klijakub commented
Mobile view issue:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/4997537/191527303-c48efe30-a139-48a4-b262-8296b80fc7ab.png">

2022-09-21 14:15 UTC, klijakub commented on assets/js/asciinema-player.min.js
> +var AsciinemaPlayer=function(A){"use strict";function g(A,g,I,B,Q,C,E){try{var t=A[C](E),e=t.value}catch(A){return void I(A)}t.done?g(e):Promise.resolve(e).then(B,Q)}function I(A){return function(){v
Remove console.debug

2022-09-21 14:38 UTC, klijakub commented
Export in better quality:
![image](https://user-images.githubusercontent.com/4997537/191534144-6ec6dc91-7b9e-443d-ab73-65b03eced5c3.png)

2022-09-26 08:26 UTC, ArkuVonSymfon requested changes

2022-09-26 08:26 UTC, ArkuVonSymfon commented on _includes/scripts.html
> +    { cols: 101, rows: 24, autoPlay: true }
Was this one done on purpose with different cols and rows? Any others have the same like "151" and "36"

2022-09-26 08:26 UTC, ArkuVonSymfon commented on _includes/styles.html
> +/>
end line

2022-09-26 08:26 UTC, ArkuVonSymfon commented on _data/patcher.yml
> +  planned: Standalone product
end line

2022-09-26 08:26 UTC, ArkuVonSymfon commented on assets/js/slider.js
> +});
end line

2022-09-26 08:26 UTC, ArkuVonSymfon commented on pages/patcher/_hero.html
> +</div>
end line

2022-09-26 08:26 UTC, ArkuVonSymfon commented on pages/patcher/_how-it-works.html
> +</script>
end line

2022-09-26 08:26 UTC, ArkuVonSymfon commented on pages/patcher/_patcher-table.html
> +</div>
end line

2022-09-26 08:26 UTC, ArkuVonSymfon commented on pages/patcher/_video.html
> +</script>
end line

2022-09-26 08:26 UTC, ArkuVonSymfon commented on pages/patcher/_slider.html
> +</div>
end line

2023-05-08 10:05 UTC, closed without merging