patcher update
Altalogy/gruntwork-io.github.io pull request #8
Opened 2023-05-08 10:01 UTC by lubiarz-oliwia

patcher page, early access form page, great news page, how it works page update, landing zone page update, reference architecture page update, archive compliance page update, pricing page update

2023-05-08 12:25 UTC, ArkuVonSymfon requested changes

2023-05-08 12:25 UTC, ArkuVonSymfon commented on _data/initial-setup-how-it-works.yml
> +      <a href="/patcher" target="_blank">Check out how simple it is.</a>
Just for double check if `/patcher` should be opened in a new window / tab

2023-05-08 12:25 UTC, ArkuVonSymfon commented on _data/patcher-features.yml
> +  description: We keep the Infrastructure as Code Library and Reference Architecture up to date with the latest best practices, security releases, tool versions (e.g., latest versions of Terraform, K
NIT: Break line

2023-05-08 12:25 UTC, ArkuVonSymfon commented on pages/patcher/_hero.html
> +          " class="label-beta label-small">
break line after "

2023-05-08 12:25 UTC, ArkuVonSymfon commented on pages/patcher/_hero.html
> +      <img class="floating-img-patcher" src="/assets/img/patcher/hero@3x.png"
```suggestion
      <img 
          class="floating-img-patcher"
          src="/assets/img/patcher/hero@3x.png"
```

2023-05-08 12:25 UTC, ArkuVonSymfon commented on pages/patcher/_how-it-works.html
> +<script>
every JS script should be started after the document so add "document ready" or "on load"

2023-05-08 12:25 UTC, ArkuVonSymfon commented on pages/pricing/_standard-pricing.html
> +    <hr />
in HTML5 we don't need `/` in `<hr>` or `<br>` please check other examples in project but I think it can be as `<hr>`

2023-05-09 01:03 UTC, josh-padnick commented
This looks pretty good! I have just a few small final requests and then I think we're set!

1. In the webform, the checkboxes can only be checked if you click on the checkbox, but not the text associated with the checkbox. Could you update it so that when you click on the text, it selects/deselects the associated checkbox?

    <img width="501" alt="image" src="https://user-images.githubusercontent.com/4295964/236967726-4c80ad0d-d5b7-402c-b626-d517499805d9.png">

2. Could you add a field for "Title" after "Name" and before "Company Email Address"
3. "Company email adress" is misspelled. It should be "Company Email Address" (with two d's)

2023-05-11 23:39 UTC, josh-padnick commented
Folks, I think we're all set here! I'm pushing this live now!

2023-05-11 23:40 UTC, merged