Consulting
Altalogy/gruntwork-io.github.io pull request #9
Opened 2023-05-23 11:52 UTC by lubiarz-oliwia

This PR adds:
- consulting page; 
- consulting form page;
- updated content for FAQ page, Home Page, and How it Works page;
- consulting page added in the navbar, footer

2023-05-24 11:13 UTC, klijakub requested changes

2023-05-24 11:13 UTC, klijakub commented on pages/consulting-form/_input-check.html
No checkboxes in the consulting form, we can remove it

2023-05-24 11:13 UTC, klijakub commented on pages/consulting-form/index.html
> +slug: contact
`slug: consulting-form`

2023-05-24 11:13 UTC, klijakub commented on pages/consulting/_comparison.html
> +            <p class="p-txt" style="color: #BFBFBF;">{{{{feature.gruntwork_consulting_description}}</p>
Why 4 `{{{{` ?

2023-05-25 13:51 UTC, klijakub approved these changes

2023-05-26 06:25 UTC, ArkuVonSymfon approved these changes
You can repair the spacing issues but after all LGTM

2023-05-26 06:25 UTC, ArkuVonSymfon commented on assets/js/consulting.js
> +   (function($) {
some weird tabs spacing

2023-05-26 06:25 UTC, ArkuVonSymfon commented on pages/consulting-form/_form.html
> +">
the same

2023-07-10 06:34 UTC, closed without merging

2023-07-10 06:34 UTC, lubiarz-oliwia commented
outdated